/* GENERATED by tools/stealthburner/gen_sprites.py -- do not edit.
 *
 * The bed sprite is the original gif_qgling bed art with the toolhead
 * erased. Its top face is a trapezoid; these are its corners in the
 * sprite's own pixel coordinates, which is what the runtime projection
 * maps printer X/Y onto:
 *
 *      (29,0) ______________ (129,0)     back  (Y max)
 *              /                \
 *             /                  \
 *   (0,13) /____________________\ (159,13)   front (Y min)
 *
 * Head sprites run smallest (far) to largest (near); index maps linearly
 * onto that same front..back axis, so the head foreshortens by exactly the
 * factor the bed does. */
#ifndef TOOLHEAD_SCENE_H
#define TOOLHEAD_SCENE_H

#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif
#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#define SB_BED_W        160
#define SB_BED_H        24

#define SB_BED_BACK_Y   0
#define SB_BED_BACK_X0  29
#define SB_BED_BACK_X1  129
#define SB_BED_FRONT_Y  13
#define SB_BED_FRONT_X0 0
#define SB_BED_FRONT_X1 159

#define SB_HEAD_COUNT   23

extern const lv_img_dsc_t sb_bed;
extern const lv_img_dsc_t * const sb_head[SB_HEAD_COUNT];

#endif /* TOOLHEAD_SCENE_H */
